### ISSUE TITLE
[REQUEST] adding Svelte client

### ISSUE THREAD

**Issue by lgs** [stripe-samples/subscription-use-cases#101]
Other that vanillajs and React, should be great having Svelte client front-end with tailwind.

**Comment by cjavilla-stripe** [comment]
Thanks for the feedback, @lgs! We don't have any official support for Svelte, but would welcome community contributions for that framework. We explicitly avoid adding CSS frameworks as these samples are purely to be used for reference for how to implement the Stripe features and the CSS framework doesn't add any value and can distract from the actual demo.

**Comment by nosovk** [comment]
Svelte is not an CSS framework ;)

**Comment by cjavilla-stripe** [comment]
@nosovk right. I was referring to tailwind :)
