### ISSUE TITLE
[REQUEST]  log-in integration

### ISSUE THREAD

**Issue by lgs** [stripe-samples/subscription-use-cases#102]
Subscription use case is useful, 
but could be even more if you could integrate it with a full flagged sign-up/sign-in method.

**Comment by cjavilla-stripe** [comment]
Authentication is really tech stack dependent. It's not feasible at this time to show full end to end examples with authentication with all the popular authentication mechanisms across all stacks and frameworks. Instead, we focus on just the Stripe pieces and use a very light weight auth based on a cookie with the customer's ID.
