### ISSUE TITLE
Change to Intraday schema

### ISSUE THREAD

**Issue by niceandsimple4** [stripe-samples/subscription-use-cases#119]
Price needs to be removed from the schema

**Comment by cjavilla-stripe** [comment]
Hey @niceandsimple4. Can you clarify what you mean by schema? do you mean the example .env file?

**Comment by niceandsimple4** [comment]
> Hey @niceandsimple4. Can you clarify what you mean by schema? do you mean the example .env file?

Apologies wrong project will delete now.
