### ISSUE TITLE
Sample not currently supported by the CLI

### ISSUE THREAD

**Issue by ED-txtify** [stripe-samples/subscription-use-cases#12]
As per the instructions - when you run "stripe samples create subscriptions-with-fixed-price"

You get:

"The sample provided is not currently supported by the CLI: subscriptions-with-fixed-price
To see supported samples, run 'stripe samples list'"

If I do run: stripe samples list - I get:

"A list of available Stripe Samples:

accept-a-card-payment
Learn how to accept a basic card payment
Repo: https://github.com/stripe-samples/accept-a-card-payment

adding-sales-tax
Learn how to use PaymentIntents to build a simple checkout flow
Repo: https://github.com/stripe-samples/adding-sales-tax

au-becs-debit-payment
Collecting AU BECS Direct Debit mandates and payments
Repo: https://github.com/stripe-samples/au-becs-debit-payment

card-brand-choice
Supporting Card Brand Choice with Stripe.
Repo: https://github.com/stripe-samples/card-brand-choice
.........
"

I am running this on:
4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
Standard LAMP installation

**Comment by ctrudeau-stripe** [comment]
Hello @ED-txtify, thank you for the bug report. We renamed this repo to support more use cases. You can use the CLI by using the following command: 

`stripe samples create subscription-use-cases`
