### ISSUE TITLE
3D secure challenge flow is not working.

### ISSUE THREAD

**Issue by takeharu** [stripe-samples/subscription-use-cases#23]
Hi,

I'm running `fixed-price-subscriptions` in my local environment (ruby/server.rb and vanillajs). 

This works fine for `424242424242424242`, however, when using the 3D Secure challenge flow card number `4000000000003220`, I get an error on the way and don't get the dialog.

When executing the `createSubscription` function in `script.js`, The server returns an error response. Then, in the Promiss, `return response.json();`, the Json A Parse error occurs.

What is the best way to fix this?

**Comment by ctrudeau-stripe** [comment]
Hello @takeharu, 

Have you configured the .env file with the products? This error will happen when there are no prices configured in Stripe. 

2. Create Products and Plans on Stripe

This sample requires a Price ID to create the subscription. Products and Plans are objects on Stripe that you use to model a subscription.

You can create Products and Prices in the Dashboard or with the API. Create a Price to run this sample and add it to your .env.

**Comment by takeharu** [comment]
Hello @ctrudeau-stripe,  

Thanks for the reply. 
But it seems to be a different problem.

I created a new product and set the environment variable PriceID (`BASIC` and `PREMIUM`) in the .env file.
But I get the same error.

If it were the problem you're talking about, `4242424242424242` should also cause an error, but it doesn't.

If I run it in node.js, I get the following error (I get the same message in ruby)

```
(node:88544) UnhandledPromiseRejectionWarning: \n
Error: Payment for this subscription requires additional user action before \n
it can be completed successfully.  \n
Please refer to the use of the `enable_incomplete_payments` parameter  \n
here: https://stripe.com/docs/billing/lifecycle#incomplete-opt-in
    at Function.generate (/fixed-price-subscriptions/server/node/node_modules/stripe/lib/Error.js:50:16)
    at IncomingMessage.<anonymous> (/fixed-price-subscriptions/server/node/node_modules/stripe/lib/StripeResource.js:168:39)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:74:11)
```

The response has a Status Code of `402 Payment Required`

I don't know what `enable_incomplete_payments` means.

**Comment by takeharu** [comment]
@ctrudeau-stripe,

I've solved the problem.

I did not have the switch to enable 3D Secure turned on in the dashboard settings menu.

I was able to get the dialog and continue the process successfully.

Thank you for your response.
