### ISSUE TITLE
Random arguments in promise flow

### ISSUE THREAD

**Issue by markpradhan** [stripe-samples/subscription-use-cases#24]
In file: `https://github.com/stripe-samples/subscription-use-cases/blob/master/fixed-price-subscriptions/client/react/src/PaymentForm.js`

```
        .then((result) => {
          return {
            // Use the Stripe 'object' property on the
            // returned result to understand what object is returned.
            subscription: result,
            paymentMethodId: paymentMethodId,
            priceId: productSelected.name,
          };
        })
        // Some payment methods require a customer to do additional
        // authentication with their financial institution.
        // Eg: 2FA for cards.
        .then(handleCustomerActionRequired)
```

```
  function handleCustomerActionRequired({
    subscription,
    invoice,
    priceId,
    paymentMethodId,
    isRetry,
  }) {
```

Where does 'invoice', 'isRetry' come from??

**Comment by markpradhan** [comment]
Can any front end dev at stripe please make a payment solution given the examples online.
I'm walking through the react implementation of `https://stripe.com/docs/billing/subscriptions/fixed-price?lang=node`. 
There are too things that are wrong, function names that differ etc...

**Comment by markpradhan** [comment]
Ok the issue stems from both functions "retryInvoiceWithNewPaymentMethod" and "createSubscription" eventually calling "handleCustomerActionRequired". Retry... actually does call the relevant fn with those parameters.

**Comment by markpradhan** [comment]
Also another detail, the nodejs docs (https://stripe.com/docs/api/subscriptions/create) show `"latest_invoice": null,` in the example response.

So in the examples the following might throw an unexpected error.
`let paymentIntent = subscription.latest_invoice.payment_intent -> will throw an error.`

**Comment by ctrudeau-stripe** [comment]
Hey @markpradhan, the parameters are used later in the flow when the payment is declined. If the payment is declined the payment is retired on the invoice from the subscription. This sample is meant to be a reference implementation and the guide helps walk through adding subscriptions to your existing application where something is already created. The sample uses the [expand parameter](https://stripe.com/docs/expand) and the [latest_invoice ](https://github.com/stripe-samples/subscription-use-cases/blob/master/fixed-price-subscriptions/server/node/server.js#L106) won't be null. This is to capture the payment intent in order to accept payments that require 3D secure.

**Comment by markpradhan** [comment]
I understand, but what about original post, did you take a look at that? I hope you understand the code snippet i referenced will always fail?

**Comment by markpradhan** [comment]
The function in question is also called whenever a subscription is created for the first time in the examples.

**Comment by ctrudeau-stripe** [comment]
Can you post the error you are getting from the function? I don't understand where it is failing with the reference.

**Comment by markpradhan** [comment]
Ok, my bad, it actually works :D.

**Comment by markpradhan** [comment]
But still confusing when looking at the docs. I was using it with typescript...

**Comment by ctrudeau-stripe** [comment]
Confusing that it takes multiple parameters from different function calls?

**Comment by markpradhan** [comment]
As the example is written, the function only ever gets called with`{ subscription, paymentMethodId, priceId}`.

**Comment by markpradhan** [comment]
In the vanilla js example, it does get called with different arguments. As for the react example, the extra arguments, just make it confusing.

**Comment by markpradhan** [comment]
This is what i thought at first glance:

"Wait, so this function will get called somehow again with those arguments.. but why and where?
Huh? Will stripe restart the createSubscription flow by itself again? What is actually going on? Should i disregard? Should i investigate more? Why is there a function defined with seemingly random arguments that only gets called once?"

It was only later i found out it was copied straight from the vanilla-js examples where it actually is used in a sensible way.

Examples should clear up confusion, not add to it. I rest my case.

**Comment by ctrudeau-stripe** [comment]
This is great feedback. Do you think it'd be better to have two separate functions if there is repeated logic?

**Comment by markpradhan** [comment]
I would define the function in a utility file and export it. Never would i define a function for multiple use, but only use it once ever.

Whenever you define a function in a react component, you either pass it down to its children, or use it there. Since its only used once in the example, theres no case to be made for repeated logic.

What also doesn't help is that the react examples do not have that retry functionality (as far i've checked the docs).
So looking at the react example, i would suggest the following.

Group the utility functions into an utils file OR remove parts of the code that just do not matter. 
Remember this is an example, not a catch all case. And if it should be a catch all case, actually make it catch all cases.
