### ISSUE TITLE
Inconsistent SDK usage.

### ISSUE THREAD

**Issue by michaeldnelson** [stripe-samples/subscription-use-cases#265]
# Bug report

## Describe the bug

subscription-cancel is inconsistent with the rest of the sdk usage. 

## To Reproduce

View this repo

```php
    $subscription = $stripe->subscriptions->retrieve($body->subscriptionId);
    $subscription->delete();
````

## Expected behavior

```php
    $subscription = $stripe->subscriptions->cancel($body->subscriptionId);
````

## Additional context

It looks like these are equivalent calls and the second is consistent with other examples in the repo.  If these calls are not equivalent please let me know.

**Comment by cjavilla-stripe** [comment]
You're right. I don't recall when that pattern changed in the PHP SDK, but the sample was likely written before that time. The API reference reflects your expected behaviour, which I think is right: https://stripe.com/docs/api/subscriptions/cancel?lang=php. 

Going to experiment now.

**Comment by cjavilla-stripe** [comment]
Updated the fixed price example. Thanks again!
