### ISSUE TITLE
Fixed Price Subscription Sample creating new payment methods instead of updating previous payment method.

### ISSUE THREAD

**Issue by syarkhan** [stripe-samples/subscription-use-cases#31]
# Bug report

## Describe the bug

Fixed Price Subscription Sample creating new payment methods instead of updating previous payment method.

## To Reproduce

1. Use card 4000000000000341 to test it and fails to charge customer. 
2. Using it again or add a new card, it creates a new payment method.

## Expected behavior

The payment method should be updated if a customer already has a payment method attached to his account.

**Comment by ctrudeau-stripe** [comment]
I'm pretty sure this is by design. Instead of updating the payment method we create a new one. Can you confirm thats what you’re seeing and also which server language you’re using?

**Comment by syarkhan** [comment]
I am sorry about that. Yes, it creates a new one instead of updating the payment method and if someone wants to update the payment method, then they should first check if a payment method exists for a customer and then update it or create a new one.
