### ISSUE TITLE
Fixed-price-subscriptions sample site fails

### ISSUE THREAD

**Issue by KenCox** [stripe-samples/subscription-use-cases#32]
Fixed-price-subscriptions sample site fails with the following error:
Error: ENOENT: no such file or directory, stat '/sandbox/client/index.html'

## To Reproduce
1. Navigate to https://github.com/stripe-samples/subscription-use-cases
2. Scroll down to the Demo area.
3. In the fixed-price-subscriptions column, click Sample.

Instead of the sample site, the following error appears:
https://xt7b9.sse.codesandbox.io/
Error: ENOENT: no such file or directory, stat '/sandbox/client/index.html'

**Comment by ctrudeau-stripe** [comment]
Hello @KenCox, thank you for the report. The demo is back working.
