### ISSUE TITLE
Successful retried payments not returning success status

### ISSUE THREAD

**Issue by GraemeFulton** [stripe-samples/subscription-use-cases#39]
# Bug report
Possible issue in [fixed-price-subscriptions](https://github.com/stripe-samples/subscription-use-cases/tree/master/fixed-price-subscriptions) example.

## Describe the bug

When a card is declined, and the customer retries with a new card, the payment status on the invoice (returned from [retry-invoice](https://github.com/stripe-samples/subscription-use-cases/blob/master/fixed-price-subscriptions/server/node/server.js#L112)) is `open`, and payment status never changes to `success`.
 
## To Reproduce

In React.js mode:

1. On the checkout, enter the payment fail test card `4000000000000341 `
2. Press submit, and the error response is as declined, as expected.
3. Enter the test card that should succeed `4242424242424242 `
4. After `onSubscriptionComplete`, in `setAccountInformation`, `result.subscription.status` = `open`
 

## Expected behavior

1. On the checkout, enter the payment fail test card `4000000000000341 `
2. Press submit, and the error response is as declined, as expected.
3. Enter the test card that should succeed `4242424242424242 `
4. After `onSubscriptionComplete`, in `setAccountInformation`, `result.subscription.status` = `success` 

## Solution
To solve it, I have modified `onSubscriptionComplete` with an extra check with `retrievePaymentIntent` for payments that have previously failed (see below). 

```
    async function onSubscriptionComplete(result) {

        if (result && !result.subscription) {
            //this is hit when a payment failed and is retried, so there's no subscriptionon the result
            const subscription = { id: result.invoice.subscription };
            result.subscription = subscription;
            localStorage.removeItem('latestInvoiceId');
            localStorage.removeItem('latestInvoicePaymentIntentStatus');

            let paymentIntent = result.invoice.payment_intent

           //double check if the payment has been successful
            await stripe
                .retrievePaymentIntent(paymentIntent.client_secret)
                .then((confirmationResult) => {
                    console.log(confirmationResult)
                    if (confirmationResult.error) {
                        // start code flow to handle updating the payment details
                        // Display error message in your UI.
                        // The card was declined (i.e. insufficient funds, card has expired, etc)
                        throw confirmationResult.error;
                    } else {
                        if (confirmationResult.paymentIntent.status === 'succeeded') {
                            console.log('succeeded')
                          //do something like this to update payment status, not working properly though
                           result.invoice.subscription.status = confirmationResult.paymentIntent.status
                        }
                    }
                });
        }
     
        setAccountInformation(result);

        // Change your UI to show a success message to your customer.
        // successful if (accountInformation.subscription.status == 'active' || accountInformation.subscription.status =='succeeded')
    }

```

## System information

- OS: [e.g. macOS]
- Browser (if applies) [chrome]
- Server environment [ Node]

## Additional context

Overall, I'm not sure this is even an issue, and doing this extra check is necessary..it depends if `open` status on an invoice means the subscription has succeeded.

**Comment by ctrudeau-stripe** [comment]
Hello @GraemeFulton, thank you for a great write up. The current example verifies the payment has been successful by checking if it is a retry and `requires_payment_method` on [Line 50 here](https://github.com/stripe-samples/subscription-use-cases/blob/master/fixed-price-subscriptions/client/react/src/PaymentForm.js#L50). [On line 63](https://github.com/stripe-samples/subscription-use-cases/blob/master/fixed-price-subscriptions/client/react/src/PaymentForm.js#L50) the result of `stripe.confirmCardPayment` is the updated payment intent showing success. This should avoid having to do another API call to retrieve the payment intent and can check the status === succeeded there. If this payment intent succeeds the invoice will automatically update and put the subscription in active state.

**Comment by GraemeFulton** [comment]
Oooh I see! Thanks a lot, it was there all along 🙈, - so I just need the check where you highlight. 
I was confused because in component render [line 286](https://github.com/stripe-samples/subscription-use-cases/blob/master/fixed-price-subscriptions/client/react/src/PaymentForm.js#L286), it checks for account information before redirecting, which sometimes isn't 'success', and I wanted to redirect when success only. That solves it though! thank you!
