### ISSUE TITLE
Expected header does not match header sent from Stripe test harness

### ISSUE THREAD

**Issue by Russ-K** [stripe-samples/subscription-use-cases#47]
# Bug report

## Describe the bug

When using the Stripe test harness to send events to the webhook endpoint, the "stripe-signature" header is sent with capitalised words, i.e. "Stripe-Signature".

This file is incorrect:
https://github.com/stripe-samples/subscription-use-cases/blob/master/fixed-price-subscriptions/server/node/server.js

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Provision a webhook
2. Setup a webhook here: https://dashboard.stripe.com/test/webhooks/
3. Send a test webhook event

## Expected behavior

The demo code should properly reflect the actual header
https://github.com/stripe-samples/subscription-use-cases/blob/master/fixed-price-subscriptions/server/node/server.js

## System information

- AWS lambda function

## Additional context

This was when using "Viewing test data", I'm yet to try in live.

**Comment by cjavilla-stripe** [comment]
Thanks again for the contribution!
