### ISSUE TITLE
Bug: wrong ConfirmCardPayment error handling

### ISSUE THREAD

**Issue by jpinho** [stripe-samples/subscription-use-cases#53]
https://github.com/stripe-samples/subscription-use-cases/blob/c0173f3fe2ba723fdab5cb7ac82312a681b95117/fixed-price-subscriptions/client/vanillajs/script.js#L290

If the confirm card payment operation fails a subscription already exists, no we need to update our client state to reflect the failed payment intent status.

That can be achieve by adding this code on error handler:

```
if (result.error) {
    // start code flow to handle updating the payment details
    // The card was declined (i.e. insufficient funds, card has expired, etc)
    if (result.error.payment_intent.status === 'requires_payment_method') {
        sessionStorage.setItem('latestInvoiceId', subscription.latest_invoice.id);
        sessionStorage.setItem('latestInvoicePaymentIntentStatus', result.error.payment_intent.status);
    }
    throw result.error;
}
```

Also, session storage seems a much better approach to persist the user session state than the local storage.

**Comment by jpinho** [comment]
Let me know if you want me to fix it, I've some time this weekend.

**Comment by cjavilla-stripe** [comment]
We've updated the approach to this and no longer use sessionStorage like this. Thanks for the report!
