### ISSUE TITLE
invoice.retrieveUpcoming cannot set property `subscription_prorate`

### ISSUE THREAD

**Issue by damiandominella** [stripe-samples/subscription-use-cases#58]
# Bug report

## Describe the bug

When trying to implementing the `/retrieve-upcoming-invoice` endpoint and calling the method `stripe.invoices.retrieveUpcoming(...)` in **typescript** the property `subscription_prorate: true` cannot be set as the example describes. 

The error is: `Argument of type '{ subscription_prorate: boolean; customer: any; subscription: any; subscription_items: ({ id: string; deleted: true; } | { price: string; deleted: false; })[]; }' is not assignable to parameter of type 'InvoiceRetrieveUpcomingParams'`

## To Reproduce

```typescript
// Retrieve invoice
  const invoice = await stripe.invoices.retrieveUpcoming({
    subscription_prorate: true, // This gives an error
    customer: req.body.customerId,
    subscription: req.body.subscriptionId,
    subscription_items: [
      {
        id: subscription.items.data[0].id,
        deleted: true,
      },
      {
        price: process.env[req.body.newPriceId],
        deleted: false,
      },
    ],
  });
```

**Comment by EricSei** [comment]
I had the same issue. When I looked up the Invoices API doc, there is no parameter for `subscription_proprate`

**Comment by cjavilla-stripe** [comment]
This issue is stale and that field was removed from the sample. Thanks again for raising. For posterity, the field was renamed and is now `subscription_proration_behavior`.

https://stripe.com/docs/api/invoices/upcoming?lang=dotnet#upcoming_invoice-subscription_proration_behavior

**Comment by audiBookning** [comment]
`subscription_prorate: true,` is still in the code of [usage-based-subscriptions](https://github.com/stripe-samples/subscription-use-cases/blob/master/usage-based-subscriptions/server/node/server.js#L150).

**Comment by lythesia** [comment]
> subscription_proration_behavior

+1
