### ISSUE TITLE
Subscriptions incomplete despite payments successful

### ISSUE THREAD

**Issue by willvlad** [stripe-samples/subscription-use-cases#79]
I've been following the paymentintent SCA docs, but can't get the subscriptions to become active.

They keep showing Incomplete "This subscription will expire tomorrow unless the first payment is completed."

Even though the payment has been taken!

My flow is as follows:
Fetch stripeUrl from front-end => create paymentIntent, customer, plan, subscription on the server
=> send intent.client_secret to the client => Verify SCA => Payment made, but subscription is still showing "incomplete"
```
const subscription = await stripe.subscriptions.create({
          customer: customer.id,
          items: [
            {
              plan: plan.id,
            },
          ],
          // trial_from_plan: true,
          expand: ["latest_invoice.payment_intent"],
        });
```
For some reason subscription is not tracking the payment status. Any ideas how to make it do so?

**Comment by cjavilla-stripe** [comment]
Hey @willvlad. The payment intent will be created for you so you shouldn't be creating one of those. Instead, the ID of the Subscription's latest invoice's payment intent's client_secret should be passed back to the client to confirm.

**Comment by willvlad** [comment]
@cjavilla-stripe I got that, what I found confusing is why subscription payment intent invoice is being created as automatic confirmation, while paymentIntent proper is manual confirmation and handleCardAction is used vs confirmCardPayment. Which one is to be used where is very poorly explained in the docs. 

Also, the subscription payment intent is just for that single invoice, what about future period invoices? Are they going to have their own SCA done? If so, how? How is the subscription then different from 12 or whatever manual payments? Is that the user experience Stripe thinks its users want when they do subscriptions?

**Comment by cjavilla-stripe** [comment]
Good questions. The default confirmation method for a PaymentIntent is automatic [0] which is also what Subscription's use and there isn't a way to modify this behavior. This means that the Subscription create flow will attempt to create and confirm the payment intent and only in the case that it requires action from the user will it need to go through confirmCardPayment. 

When the customer is "on session" meaning they are on your site, there are specific rules for SCA that apply and one of those is collecting permission from the user to collect payment. For subsequent invoices, while it's possible that some next action will be required, it should be very rare and these payments fall into a bucket called MIT or merchant initiated transactions. There are some more details about how this exemption is applied, but the basic premise is that if you got permission to start the subscription, then most card issuers (the customer's bank) will allow you to collect payments later on a recurring basis without needing to push the customer through the SCA flow. 

We do expect that sometimes a later recurring payment will require next action. In those cases, you'll need to pull the customer back on session and use the confirmCardPayment with the failed invoice's payment intent. Hope that helps.

[0] https://stripe.com/docs/api/payment_intents/create#create_payment_intent-confirmation_method

**Comment by willvlad** [comment]
My use case is super simple: user customises a subscription and enters card details, all of which gets sent to the server => Server creates a new plan, product, customer and subscription => Sends intent (from Subscription) back to FE => If required, SCA is performed and the subscription is confirmed. I've followed this approach https://stripe.com/docs/payments/accept-a-payment-synchronously that I am adapting to subscriptions. As you can see, it has a second call that confirms the intent on the server. How should I handle it with subscription payment intent?

**Comment by cjavilla-stripe** [comment]
Unfortunately, manual server side confirmation isn't supported when starting subscriptions.
