### ISSUE TITLE
Huge Security Issue with Examples

### ISSUE THREAD

**Issue by anatolzak** [stripe-samples/subscription-use-cases#80]
I have contacted stripe support regarding a huge security issue I have found in the examples.

Support completely misunderstood me and were no help unfortunately. Should I describe the security issue here or should I write it to someone privately?

**Comment by cjavilla-stripe** [comment]
Hey @anatolzak if you'd like to send me a DM on twitter @cjav_dev I'd be happy to chat. These examples are meant to just show the code required to build the integration, but should never be used in production with the key management as is.
