### ISSUE TITLE
Code sandbox error for usage based subscription example

### ISSUE THREAD

**Issue by manvinder01** [stripe-samples/subscription-use-cases#84]
The [codesandbox.io link](https://codesandbox.io/s/github/stripe-samples/subscription-use-cases/tree/master/per-seat-subscriptions) for the usage-based subscription example is showing a container error

also the link refers to the per-seat model which may have something to do with this error.

**Comment by dawn-stripe** [comment]
thanks @manvinder01: I've updated the link the README for the usage-based example.  (It was pointing to the per-seat example which unfortunately is still displaying a container error)
