### ISSUE TITLE
fixed-price-subscriptions - Sandbox 502: Bad Gateway

### ISSUE THREAD

**Issue by Whateverinc** [stripe-samples/subscription-use-cases#89]
Just noticed when trying to view the "fixed-price-subscriptions", not that big of a problem, but just wanted to point it out.

**Comment by dawn-stripe** [comment]
Thanks @Whateverinc, this should be fixed now, let us know if you have any problems reaching the sandbox.

**Comment by Whateverinc** [comment]
It works!!! Now, for some reason the preview styling is no longer there. Not that I need it, I like this version a lot, but it looks different from the screenshots.

![Screen Shot 2021-02-09 at 10 14 24 PM](https://user-images.githubusercontent.com/8814394/107463698-4c6ae280-6b24-11eb-860b-8ec5da6c81e5.png)

**Comment by cjavilla-stripe** [comment]
Yeah the styles were removed along with tailwind to simplify the sample. We'll update the screenshots.
